version: '3.6'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'nestjs_shop'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
